CREATE TABLE ##TABELA02 (ID VARCHAR(10), NOME VARCHAR(30));
INSERT INTO ##TABELA02 VALUES ('1','JOÃO');
INSERT INTO ##TABELA02 VALUES ('2','KATIA');
SELECT * FROM ##TABELA02;


INSERT INTO ##TABELA02 VALUES ('3','JORGE');
SELECT * FROM ##TABELA02;